# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process.

# Basic Site Settings
locale                   : "en-US"
site_theme               : "air" # Currently available options are "default", "air"
title                    : "Jose A. Guridi"
title_separator          : "-"
name                     : &name "Jose A. Guridi"
description              : &description "PhD Candidate in Information Science at Cornell University. Researching AI governance, policy, and participatory processes."   # Update this with a general description of your site, this is the default if not overridden by a page
url                      : "https://jaguridi.github.io" # The base hostname & protocol for your site
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "jaguridi/jaguridi.github.io"

# Site Author - The following control what appear as part of the author content on the side bar.
#               If a field is blank the icon and link will not appear, otherwise it will be shown.
#               Additional customization can be done by editing /_includes/author-profile.html
author:
  # Biographic information
  avatar           : "profile.png" # Make sure to upload your photo to /images/profile.png
  name             : "Jose A. Guridi"
  pronouns         : "he/him"  
  bio              : "PhD Candidate in Information Science, Cornell University"
  location         : "Ithaca, NY & Santiago, Chile"
  employer         : "Cornell University"
  uri              : # URL
  email            : "jg2222@cornell.edu" 

  # Academic websites
  academia         : # URL
  arxiv            : # URL 
  googlescholar    : "https://scholar.google.com/citations?user=P5xFVC4AAAAJ&hl=en"
  inspire-hep      : # URL
  impactstory      : # URL
  orcid            : "https://orcid.org/0000-0003-0543-699X"
  semantic         : # URL
  pubmed           : # URL
  researchgate     : "https://www.researchgate.net/profile/Jose-Guridi-2"
  scopus           : # URL

  # Repositories and software development
  bitbucket        : # Username 
  codepen          : # Username
  dribbble         : # Username
  github           : "jaguridi"
  kaggle           : # Username  
  stackoverflow    : # User number 

  # Social media
  artstation       : # Username
  bluesky          : # Username
  facebook         : # Username
  flickr           : # Username
  foursquare       : # Username
  goodreads        : # Username
  google_plus      : # Username
  keybase          : # Username
  instagram        : # Username
  lastfm           : # Username
  linkedin         : "jaguridi" # Your LinkedIn username
  mastodon         : # URL
  medium           : # URL
  pinterest        : # Username
  soundcloud       : # Username
  steam            : # Username
  telegram         : # URL
  tumblr           : # Username
  twitter          : # Username 
  vine             : # Username
  weibo            : # Username
  wikipedia        : # Username
  xing             : # Username
  youtube          : # Username
  zhihu            : # Username

  # Custom Links (For CV and Consulting Firm)
  links:
    - label: "CV"
      url: "files/Jose_Guridi_CV.pdf" # Ensure you renamed your PDF to this
      icon: "fas fa-fw fa-file-pdf"
    - label: "Foresight Consulting"
      url: "http://www.foresight.cl/"
      icon: "fas fa-fw fa-briefcase"

# Publication Category - The following the list of publication categories and their headings
publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'    
  conferences:
